version: "3.7"

services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: typegraphql
      POSTGRES_USER: typegraphql
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - pgdata1:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  pgdata1:
