version: "3.7"

services:
  app:
    build: .

  redis:
    image: redis:alpine

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: typegraphql
      POSTGRES_USER: typegraphql
      POSTGRES_PASSWORD: typegraphql
    ports:
      - 5432:5432
#    volumes:
#      - pg-data-graphql:/var/lib/postgresql/data

#volumes:
#  pg-data-graphql:
