name: docker image server

on:
  push:
    paths:
      - 'packages/api/*'
      - '.github/workflows/docker-image-api.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build server docker image
      run: |
        cd packages/api
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker build . --file Dockerfile --tag jasonraimondi/full-stack-graphql-server:latest
        docker push jasonraimondi/full-stack-graphql-server:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
